spring:
  security:
    user:
      name: cheng
      password: 123456
      roles: admin
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:postgresql://localhost:5432/generic_programming
          username: postgres
          password: 123456
          driver-class-name: org.postgresql.Driver
        slave_1:
          url: jdbc:postgresql://localhost:5432/generic_programming
          username: postgres
          password: 123456
          driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
        is-auto-commit: true
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    # 设置日期格式
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # 格式化输出
      indent-output: true
      # 忽略无法转换的对象
      fail-on-empty-beans: false
      # 默认只序列话非空的属性
    default-property-inclusion: non_empty
    # 允许对象忽略json中不存在的属性
    deserialization:
      fail-on-unknown-properties: false
    parser:
      # 允许出现特殊字符和转义符
      allow-unquoted-control-chars: true
      # 允许出现单引号
      allow-single-quotes: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      password:
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/rbac/**/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.rbac.entity
  # 配置mybatis的sql语句输出到console
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
